name: Deploy URL Shortener Bot to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run basic checks
      run: |
        python -c "import requests; import sqlite3; print('All imports successful')"
        # Add any additional tests specific to your bot

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render via Webhook
      run: |
        # Replace with your actual Render deploy hook URL
        curl -X POST "https://api.render.com/deploy/srv-d3ih9dbipnbc73e6m3lg?key=e3iV_mV7Kq0"
